name: "MD converter"
description: "convert markdown to html"
inputs:
  markdown:
    description: "Content of markdown file"
    required: true
outputs:
  converted: # id of output
    description: "converted markdown"
runs:
  using: "node16"
  main: "index.js"
