name: "MD converter"
description: "convert markdown to html"
inputs:
  markdown:
    description: "Content of markdown file"
    required: false
  filename:
    description: "filename of markdown, file have to be checked out"
    required: false
  spacekey:
    description: "Key of confluence space where page should be published"
    required: true
  cnflurl:
    description: "Base URL of confluence"
    required: true
  cnfluser:
    description: "Username which be used as author of page"
    required: false
  title:
    description: "Title of page"
    required: true
  apikey:
    description: "API key for authentication, must be key for user specified as cnfluser"
    required: false
  basicauth:
    description: "base64 encode username and apikey, if provided there is no need to specify username and api key separately"
runs:
  using: "node16"
  main: "dist/index.js"
