name: "MD converter"
description: "convert markdown to html"
inputs:
  markdown:
    description: "Content of markdown file"
    required: false
  filename:
    description: "filename of markdown, file have to be checked out"
    required: false
  spacekey:
    description: "Key of confluence space where page should be published"
    required: true
  cnflurl:
    description: "Base URL of confluence"
    required: true
  title:
    description: "Title of page"
    required: true
runs:
  using: "node16"
  main: "index.js"
